platform :ios, '12.0'

use_frameworks!

target 'PocketPurchasesExample' do
  pod 'PocketPurchases', :path => '../'

  pod 'SwiftLint'
  pod 'SwiftFormat/CLI'

  target 'PocketPurchasesTests' do
    inherit! :search_paths
  end
end
